/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DangNhap: typeof import('./components/DangNhap.vue')['default']
    DanhSachKhoaHoc: typeof import('./components/DanhSachKhoaHoc.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuaKhoaHoc: typeof import('./components/SuaKhoaHoc.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
    ThemKhoaHoc: typeof import('./components/ThemKhoaHoc.vue')['default']
    XoaKhoaHoc: typeof import('./components/XoaKhoaHoc.vue')['default']
  }
}
