/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dangNhap': RouteRecordInfo<'/dangNhap', '/dangNhap', Record<never, never>, Record<never, never>>,
    '/hocVien': RouteRecordInfo<'/hocVien', '/hocVien', Record<never, never>, Record<never, never>>,
    '/khoaHoc': RouteRecordInfo<'/khoaHoc', '/khoaHoc', Record<never, never>, Record<never, never>>,
    '/phanQuyen': RouteRecordInfo<'/phanQuyen', '/phanQuyen', Record<never, never>, Record<never, never>>,
    '/taiKhoan': RouteRecordInfo<'/taiKhoan', '/taiKhoan', Record<never, never>, Record<never, never>>,
  }
}
