/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dangNhap': RouteRecordInfo<'/dangNhap', '/dangNhap', Record<never, never>, Record<never, never>>,
    '/khoaHoc/danhSachKhoaHoc': RouteRecordInfo<'/khoaHoc/danhSachKhoaHoc', '/khoaHoc/danhSachKhoaHoc', Record<never, never>, Record<never, never>>,
    '/khoaHoc/suaKhoaHoc': RouteRecordInfo<'/khoaHoc/suaKhoaHoc', '/khoaHoc/suaKhoaHoc', Record<never, never>, Record<never, never>>,
    '/khoaHoc/themKhoaHoc': RouteRecordInfo<'/khoaHoc/themKhoaHoc', '/khoaHoc/themKhoaHoc', Record<never, never>, Record<never, never>>,
    '/khoaHoc/xoaKhoaHoc': RouteRecordInfo<'/khoaHoc/xoaKhoaHoc', '/khoaHoc/xoaKhoaHoc', Record<never, never>, Record<never, never>>,
  }
}
